process.env.DATABASE_URL='postgres://postgres:postgres@127.0.0.1:5432/forge_arch';
process.env.NODE_ENV='development';
import pg from 'pg';
const marker=new pg.Client({connectionString:process.env.DATABASE_URL});
await marker.connect();
const {ensureReady}=await import('/home/user/NexusHub/server/src/app.js');
await ensureReady();
await marker.query("SELECT 'PHASEMARK maint' AS m");
const t=Date.now();
const {runMaintenance}=await import('/home/user/NexusHub/server/src/services/maintenanceService.js');
await runMaintenance();
await marker.query("SELECT 'PHASEMARK END' AS m");
console.log('runMaintenance took', Date.now()-t,'ms');
await marker.end();process.exit(0);
