/**
 * Fifty UGC scripts, 10–15 seconds each, ready to render in Ad Studio.
 *
 * Every script is four beats — hook (0–2 s), problem (2–5 s), solution
 * (5–10 s), call to action (10–15 s) — and opens on a frustration, the way a
 * person talks into their phone. None explains what the shop is.
 *
 * No price is written down here. A line is a function of `$`, and `$` reads
 * the live catalogue: `$.p('ROBUX-1000')` is "€9,99" on screen and "negen euro
 * negenennegentig" in the voice. A script that compares prices says what must
 * hold in `ok` ("10.000 Robux is cheaper per 1.000 than 1.000 Robux"); when a
 * price change makes that untrue, the script is switched off with the reason,
 * never shown with a sum that no longer adds up.
 *
 * What a script may say is what the shop can prove: a username and never a
 * password for Robux (2FA on), a code by email for code products, guest
 * checkout, /track, "not delivered, money back" on /refunds, questions on
 * Discord. Nothing about speed, popularity, ratings or other shops.
 *
 * `problem` and `solution` name the picture under the line — a fake login
 * asking for a password, a stack of small top-ups, the shop's own checkout
 * field — so the video shows what the voice says.
 */

const R1 = 'ROBUX-1000', R45 = 'ROBUX-4500', R10 = 'ROBUX-10000', R22 = 'ROBUX-22500';
const V1 = 'VBUCKS-1000', V28 = 'VBUCKS-2800', V5 = 'VBUCKS-5000', V13 = 'VBUCKS-13500';
const S10 = 'STEAM-10', S25 = 'STEAM-25';

export const THEMES = {
  free: '"Gratis" Robux',
  password: 'Wachtwoord en account',
  robuxmath: 'Te veel betalen voor Robux',
  vbucks: 'V-Bucks rekenen',
  guest: 'Geen account aanmaken',
  trust: 'Komt mijn code wel?',
  parents: 'Ouders en cadeaus',
  redeem: 'Inwisselen: fouten',
  games: 'Andere games',
  myths: 'Mythes en checks',
};

/* The shop's address: written on screen, spoken in the voice. */
const site = ($) => $.site('forgemarket.nl');

/**
 * id, theme, title, sku (the product the ad sells — its card, image and link),
 * skus (every product a line reads), ok (what must be true of the prices),
 * hook / problem / solution / cta (functions of $), and the two pictures.
 * `$.size(sku)` is a pack's count read from the product name, so a line never
 * says "13.500" for a pack that is not that size.
 */
export const UGC_SCRIPTS = [
  // ── A. "Gratis" Robux ────────────────────────────────────────────────────
  { id: 'ugc-01', theme: 'free', title: 'Gratis Robux', sku: R1,
    hook: () => 'Ik dacht echt dat gratis Robux werkte…',
    problem: () => 'Je vult je naam in, dan je wachtwoord. En daarna komt er niks.',
    solution: ($) => `Echte Robux kopen kan zonder je wachtwoord. Je geeft alleen je ${$.field(R1)}.`,
    cta: ($) => `Duizend Robux, ${$.p(R1)}. ${site($)}`,
    problemProp: 'scam', solutionProp: 'username' },
  { id: 'ugc-02', theme: 'free', title: 'De generator', sku: R1,
    hook: () => 'Deze "Robux generator" wilde maar één ding van mij.',
    problem: () => 'Mijn wachtwoord. Waarom zou een verkoper dat nodig hebben?',
    solution: () => 'Op ForgeMarket vragen ze alleen je gebruikersnaam. Je wachtwoord blijft van jou.',
    cta: ($) => `Check het zelf: ${site($)}`,
    problemProp: 'scam', solutionProp: 'username' },
  { id: 'ugc-03', theme: 'free', title: 'Mijn broertje', sku: R1,
    hook: () => 'Mijn broertje klikte op een "gratis Robux"-link.',
    problem: () => 'Hij moest inloggen op een site die op Roblox leek. Die was het niet.',
    solution: () => 'Robux kopen moet zonder inloggen bij een ander. Bij ForgeMarket alleen je gebruikersnaam.',
    cta: ($) => `Laat het hem zelf zien: ${site($)}`,
    problemProp: 'scam', solutionProp: 'username' },
  { id: 'ugc-04', theme: 'free', title: 'Te mooi om waar te zijn', sku: R10,
    hook: () => 'Tienduizend gratis Robux? Nee.',
    problem: () => 'Als iets gratis is, betaal je met je account.',
    solution: ($) => `Tienduizend Robux kost op ForgeMarket ${$.p(R10)}. Gewoon een prijs, geen trucjes.`,
    cta: ($) => site($),
    problemProp: 'scam', solutionProp: 'packs', packs: [R10] },
  { id: 'ugc-05', theme: 'free', title: 'De DM', sku: R1,
    hook: () => 'Ik kreeg een DM: "Wil je gratis Robux?"',
    problem: () => 'Eerst je wachtwoord, dan "verificatie". Je kent het.',
    solution: () => 'Ik koop het liever gewoon. Alleen mijn gebruikersnaam, nooit mijn wachtwoord.',
    cta: () => 'Link in bio.',
    problemProp: 'scam', solutionProp: 'username' },

  // ── B. Wachtwoord en account ─────────────────────────────────────────────
  { id: 'ugc-06', theme: 'password', title: 'De fout van Roblox-spelers', sku: R1,
    hook: () => 'Deze fout maken Roblox-spelers steeds.',
    problem: () => 'Ze geven hun wachtwoord aan iemand die "Robux regelt".',
    solution: () => 'Dat hoeft nooit. Voor Robux op ForgeMarket is alleen je gebruikersnaam nodig.',
    cta: ($) => `${site($)}. Je wachtwoord blijft van jou.`,
    problemProp: 'scam', solutionProp: 'username' },
  { id: 'ugc-07', theme: 'password', title: '2FA', sku: R1,
    hook: () => 'Zet dit aan voordat je Robux koopt.',
    problem: ($) => `Zonder ${$.say('2FA', 'twee-staps-verificatie')} is je account een open deur.`,
    solution: ($) => `ForgeMarket levert pas als ${$.say('2FA', 'twee-staps-verificatie')} aanstaat, en vraagt alleen je gebruikersnaam.`,
    cta: ($) => `Eerst ${$.say('2FA', 'twee-staps-verificatie')}, dan ${site($)}`,
    problemProp: 'scam', solutionProp: 'checklist',
    checklist: () => ['2FA aan', 'Alleen je gebruikersnaam', 'Nooit je wachtwoord'] },
  { id: 'ugc-08', theme: 'password', title: 'Account kwijt', sku: R1,
    hook: () => 'Mijn vriend is zijn Roblox-account kwijt.',
    problem: () => 'Hij gaf zijn wachtwoord voor "goedkope Robux".',
    solution: () => 'Robux kopen kan zonder dat iemand in je account komt. Alleen je gebruikersnaam.',
    cta: ($) => site($),
    problemProp: 'scam', solutionProp: 'username' },
  { id: 'ugc-09', theme: 'password', title: 'Wat ze écht nodig hebben', sku: R1,
    hook: () => 'Wat heeft een Robux-verkoper écht van je nodig?',
    problem: () => 'Niet je wachtwoord. Niet je e-mailcode.',
    solution: ($) => `Op ForgeMarket: je ${$.field(R1)}. Meer niet.`,
    cta: ($) => `Duizend Robux, ${$.p(R1)}. ${site($)}`,
    problemProp: 'scam', solutionProp: 'username' },
  { id: 'ugc-10', theme: 'password', title: 'Moeder vroeg het', sku: R1,
    hook: () => 'Mijn moeder vroeg: "Moet je je wachtwoord geven?"',
    problem: () => 'Bij veel van die sites wel. Daarom vertrouwde ze het niet.',
    solution: ($) => `Hier niet. Je vult alleen je ${$.field(R1)} in.`,
    cta: ($) => `Laat het haar zien: ${site($)}`,
    problemProp: 'scam', solutionProp: 'username' },

  // ── C. Te veel betalen voor Robux ────────────────────────────────────────
  { id: 'ugc-11', theme: 'robuxmath', title: 'Kleine pakjes', sku: R10, skus: [R1, R10],
    ok: ($) => $.per1k(R10) < $.per1k(R1),
    hook: () => 'Ik betaalde te veel voor Robux. Door mezelf.',
    problem: ($) => `Ik kocht steeds duizend Robux voor ${$.p(R1)}.`,
    solution: ($) => `Tienduizend kost ${$.p(R10)}. Dat is ${$.per(R10)} per duizend in plaats van ${$.per(R1)}.`,
    cta: ($) => `Reken het na: ${site($)}`,
    problemProp: 'receipts', receipt: R1, solutionProp: 'packs', packs: [R1, R10] },
  { id: 'ugc-12', theme: 'robuxmath', title: 'Rekenmachine', sku: R22, skus: [R1, R22],
    ok: ($) => $.per1k(R22) < $.per1k(R1),
    hook: () => 'Pak even je rekenmachine erbij.',
    problem: ($) => `Duizend Robux: ${$.p(R1)}. Klinkt prima, toch?`,
    solution: ($) => `Bij ${$.size(R22)} Robux betaal je ${$.per(R22)} per duizend. Groter pak, lagere prijs per duizend.`,
    cta: ($) => site($),
    problemProp: 'receipts', receipt: R1, solutionProp: 'packs', packs: [R1, R22] },
  { id: 'ugc-13', theme: 'robuxmath', title: 'Elke week een beetje', sku: R10, skus: [R1, R10],
    ok: ($) => 10 * $.c(R1) > $.c(R10),
    hook: () => 'Elke week een klein beetje Robux kopen? Duur grapje.',
    problem: ($) => `Tien keer duizend Robux: ${$.m(10 * $.c(R1))}.`,
    solution: ($) => `In één keer tienduizend: ${$.p(R10)}. Dat scheelt ${$.m(10 * $.c(R1) - $.c(R10))}.`,
    cta: ($) => site($),
    problemProp: 'receipts', receipt: R1, count: 10, solutionProp: 'packs', packs: [R1, R10] },
  { id: 'ugc-14', theme: 'robuxmath', title: 'Spaar het op', sku: R45, skus: [R1, R45],
    ok: ($) => $.per1k(R45) < $.per1k(R1),
    hook: () => 'Ik wacht nu met Robux kopen. Expres.',
    problem: () => 'Elke kleine aankoop kostte me meer per duizend.',
    solution: ($) => `${$.size(R45)} Robux voor ${$.p(R45)} is ${$.per(R45)} per duizend. Duizend los is ${$.p(R1)}.`,
    cta: ($) => `Kijk zelf: ${site($)}`,
    problemProp: 'receipts', receipt: R1, solutionProp: 'packs', packs: [R1, R45] },
  { id: 'ugc-15', theme: 'robuxmath', title: 'Per duizend', sku: R22, skus: [R1, R22],
    ok: ($) => $.per1k(R22) < $.per1k(R1),
    hook: () => 'Niemand kijkt naar de prijs per duizend Robux.',
    problem: () => 'Je kijkt naar het totaal en klikt.',
    solution: ($) => `Bij ForgeMarket loopt het van ${$.per(R1)} naar ${$.per(R22)} per duizend, afhankelijk van het pak.`,
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'packs', packs: [R1, R10, R22] },

  // ── D. V-Bucks rekenen ───────────────────────────────────────────────────
  { id: 'ugc-16', theme: 'vbucks', title: 'V-Bucks-fout', sku: V13, skus: [V1, V13],
    ok: ($) => $.per1k(V13) < $.per1k(V1),
    hook: () => 'Dit kostte me jarenlang te veel V-Bucks-geld.',
    problem: ($) => `Ik kocht altijd het kleinste pak. Duizend voor ${$.p(V1)}.`,
    solution: ($) => `Het pak van ${$.size(V13)} kost ${$.p(V13)}. Dat is ${$.per(V13)} per duizend.`,
    cta: ($) => `Reken het na op ${site($)}`,
    problemProp: 'receipts', receipt: V1, solutionProp: 'packs', packs: [V1, V13] },
  { id: 'ugc-17', theme: 'vbucks', title: 'Het verschil', sku: V13, skus: [V1, V13],
    ok: ($) => $.per1k(V13) < $.per1k(V1),
    hook: ($) => `${$.per(V1)} of ${$.per(V13)}. Zelfde duizend V-Bucks.`,
    problem: () => 'Het verschil zit alleen in hoeveel je in één keer koopt.',
    solution: ($) => `Op ForgeMarket: duizend V-Bucks ${$.p(V1)}, ${$.size(V13)} voor ${$.p(V13)}.`,
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'packs', packs: [V1, V13] },
  { id: 'ugc-18', theme: 'vbucks', title: 'Battle Pass-seizoen', sku: V13, skus: [V1, V5, V13],
    ok: ($) => $.per1k(V13) < $.per1k(V1) && $.per1k(V5) < $.per1k(V1),
    hook: () => 'Elk seizoen opnieuw V-Bucks kopen?',
    problem: () => 'Steeds een klein pakje, steeds de hoogste prijs per duizend.',
    solution: ($) => `${$.size(V5)} V-Bucks voor ${$.p(V5)}, of ${$.size(V13)} voor ${$.p(V13)}. Reken het per duizend.`,
    cta: ($) => site($),
    problemProp: 'receipts', receipt: V1, solutionProp: 'packs', packs: [V1, V5, V13] },
  { id: 'ugc-19', theme: 'vbucks', title: 'Code in je mail', sku: V28,
    hook: () => 'Ik dacht dat je V-Bucks alleen in de game kon kopen.',
    problem: () => 'Daar zie je nooit wat het per duizend kost.',
    solution: ($) => `Op ForgeMarket krijg je een V-Bucks-code in je mail. Inwisselen op ${$.site('fortnite.com/vbuckscard')}.`,
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'mailcode' },
  { id: 'ugc-20', theme: 'vbucks', title: 'Mijn zakgeld', sku: V28, skus: [V1, V28],
    ok: ($) => $.per1k(V28) < $.per1k(V1) && $.c(V28) <= 2000,
    hook: () => 'Twintig euro zakgeld. Hoeveel V-Bucks?',
    problem: () => 'Bij kleine pakjes haal je er het minst uit.',
    solution: ($) => `${$.size(V28)} V-Bucks kost ${$.p(V28)}. Duizend los kost ${$.p(V1)}.`,
    cta: ($) => `Kijk wat past: ${site($)}`,
    problemProp: 'text', solutionProp: 'packs', packs: [V1, V28] },

  // ── E. Geen account aanmaken ─────────────────────────────────────────────
  { id: 'ugc-21', theme: 'guest', title: 'Weer een account', sku: R1,
    hook: () => 'Ik heb geen zin in nóg een account.',
    problem: () => 'Overal wachtwoorden, nieuwsbrieven, e-mails bevestigen.',
    solution: () => 'Bij ForgeMarket reken je af als gast.',
    cta: ($) => site($),
    problemProp: 'signup', solutionProp: 'guest' },
  { id: 'ugc-22', theme: 'guest', title: 'Snel even', sku: R1,
    hook: () => 'Ik wil gewoon even Robux kopen. Geen profiel.',
    problem: () => 'Elke site wil eerst dat je je registreert.',
    solution: ($) => `Hier niet. Afrekenen als gast, en je bestelling volg je op ${$.site('forgemarket.nl/track')}.`,
    cta: ($) => site($),
    problemProp: 'signup', solutionProp: 'guest' },
  { id: 'ugc-23', theme: 'guest', title: 'Wachtwoord vergeten', sku: V28,
    hook: () => 'Het wachtwoord van die ene site? Kwijt.',
    problem: () => 'Daarom maak ik nergens meer zomaar een account.',
    solution: () => 'ForgeMarket: afrekenen als gast.',
    cta: ($) => site($),
    problemProp: 'signup', solutionProp: 'guest' },
  { id: 'ugc-24', theme: 'guest', title: 'Nieuwsbrief', sku: S25,
    hook: () => 'Ik kocht één keer iets, en nu krijg ik elke dag mail.',
    problem: () => 'Account aangemaakt, vinkje vergeten.',
    solution: () => 'Bij ForgeMarket kun je als gast afrekenen.',
    cta: ($) => site($),
    problemProp: 'signup', solutionProp: 'guest' },
  { id: 'ugc-25', theme: 'guest', title: 'Bestelling volgen', sku: R1,
    hook: () => 'Zonder account kun je je bestelling niet volgen. Dacht ik.',
    problem: () => 'Ik wilde geen account, maar wel weten waar mijn bestelling bleef.',
    solution: ($) => `Op ${$.site('forgemarket.nl/track')} volg je hem met je bestelnummer.`,
    cta: ($) => site($),
    problemProp: 'worry', solutionProp: 'track' },

  // ── F. Komt mijn code wel? ───────────────────────────────────────────────
  { id: 'ugc-26', theme: 'trust', title: 'Bang', sku: V28,
    hook: () => 'Mijn grootste angst bij online codes kopen?',
    problem: () => 'Betalen, en dan niks krijgen.',
    solution: () => 'Bij ForgeMarket staat het zwart op wit: niet geleverd, dan geld terug.',
    cta: ($) => `Lees het zelf: ${$.site('forgemarket.nl/refunds')}`,
    problemProp: 'worry', solutionProp: 'refund' },
  { id: 'ugc-27', theme: 'trust', title: 'Eerst lezen', sku: S25,
    hook: () => 'Voordat ik ergens bestel, lees ik dit eerst.',
    problem: () => 'Het terugbetaalbeleid. Want daar zit meestal het addertje.',
    solution: ($) => `Bij ForgeMarket: niet geleverd, geld terug. Staat op ${$.site('forgemarket.nl/refunds')}.`,
    cta: () => 'Check het en beslis zelf.',
    problemProp: 'text', solutionProp: 'refund' },
  { id: 'ugc-28', theme: 'trust', title: 'Waar blijft het?', sku: R1,
    hook: () => '"Waar blijft mijn bestelling?" Nooit meer gokken.',
    problem: () => 'Bij sommige shops hoor je na je betaling niks meer.',
    solution: ($) => `Op ${$.site('forgemarket.nl/track')} zie je de status van je bestelling.`,
    cta: ($) => site($),
    problemProp: 'worry', solutionProp: 'track' },
  { id: 'ugc-29', theme: 'trust', title: 'Screenshot', sku: V28,
    hook: () => 'Ik maak altijd een screenshot van het terugbetaalbeleid.',
    problem: () => 'Je weet nooit wanneer je het nodig hebt.',
    solution: () => 'Die van ForgeMarket is kort: niet geleverd, geld terug.',
    cta: ($) => $.site('forgemarket.nl/refunds'),
    problemProp: 'text', solutionProp: 'refund' },
  { id: 'ugc-30', theme: 'trust', title: 'Vragen', sku: R1,
    hook: () => 'Ik heb altijd vragen voordat ik iets bestel.',
    problem: () => 'Bij veel shops vind je nergens een mens.',
    solution: () => 'ForgeMarket heeft een Discord waar je het gewoon kunt vragen.',
    cta: ($) => $.site('forgemarket.nl/discord'),
    problemProp: 'worry', solutionProp: 'discord' },

  // ── G. Ouders en cadeaus ─────────────────────────────────────────────────
  { id: 'ugc-31', theme: 'parents', title: 'Ouder: wachtwoord', sku: R1,
    hook: () => 'Mijn kind wilde Robux. Ik wilde zijn wachtwoord niet weggeven.',
    problem: () => 'Veel sites vragen precies dat.',
    solution: ($) => `Bij ForgeMarket alleen de ${$.field(R1)}, en ${$.say('2FA', 'twee-staps-verificatie')} moet aanstaan.`,
    cta: ($) => site($),
    problemProp: 'scam', solutionProp: 'username' },
  { id: 'ugc-32', theme: 'parents', title: 'Ouder: geen creditcard', sku: S25,
    hook: () => 'Mijn dochter vroeg om Steam-tegoed. Ik wil mijn kaart niet in haar account.',
    problem: () => 'Dan kan ze er zelf mee verder kopen.',
    solution: () => 'Een Steam Wallet-code komt in je mail. Zij wisselt hem in, jouw kaart blijft bij jou.',
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'mailcode' },
  { id: 'ugc-33', theme: 'parents', title: 'Verjaardag', sku: S25,
    hook: () => 'Wat geef je een gamer die alles al heeft?',
    problem: () => 'Je weet nooit welke game of welk item.',
    solution: () => 'Tegoed. V-Bucks, Robux of een Steam-code. Dan kiest hij zelf.',
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'packs', packs: [V28, R1, S25] },
  { id: 'ugc-34', theme: 'parents', title: 'Ouder: budget', sku: R10, skus: [R1, R10],
    ok: ($) => $.per1k(R10) < $.per1k(R1),
    hook: () => "Mijn zoon geeft z'n zakgeld uit aan kleine Robux-pakjes.",
    problem: ($) => `Duizend Robux voor ${$.p(R1)}, steeds opnieuw.`,
    solution: ($) => `Samen sparen voor tienduizend: ${$.p(R10)}. Dat is ${$.per(R10)} per duizend.`,
    cta: ($) => `Reken het samen na: ${site($)}`,
    problemProp: 'receipts', receipt: R1, solutionProp: 'packs', packs: [R1, R10] },
  { id: 'ugc-35', theme: 'parents', title: 'Geen idee wat te geven', sku: V28,
    hook: () => 'Mijn neefje wil game-tegoed. Maar voor wélke game?',
    problem: () => 'Hij speelt Fortnite én Steam-games. Ik snap er niks van.',
    solution: () => 'Een Steam- of V-Bucks-code komt in je mail. Die geef je gewoon door.',
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'mailcode' },

  // ── H. Inwisselen: fouten ────────────────────────────────────────────────
  { id: 'ugc-36', theme: 'redeem', title: 'Verkeerd account', sku: V28,
    hook: () => 'Ik heb V-Bucks op het verkeerde account gezet.',
    problem: () => 'Ingelogd op het account van mijn broertje. Weg.',
    solution: ($) => `Check op ${$.site('fortnite.com/vbuckscard')} eerst wie er ingelogd is. Dan pas de code.`,
    cta: ($) => `V-Bucks-codes op ${site($)}`,
    problemProp: 'wrong', solutionProp: 'checklist',
    checklist: () => ['Juiste account?', 'Dan pas inwisselen', 'Code uit je mail'] },
  { id: 'ugc-37', theme: 'redeem', title: 'Eerst checken', sku: V28,
    hook: () => 'Doe dit vóór je een code inwisselt.',
    problem: () => 'Een ingewisselde code krijg je niet terug.',
    solution: () => 'Kijk op welk account je ingelogd bent. Je code komt in je mail, je kiest zelf wanneer.',
    cta: ($) => site($),
    problemProp: 'wrong', solutionProp: 'mailcode' },
  { id: 'ugc-38', theme: 'redeem', title: 'Steam-saldo', sku: S25,
    hook: () => 'Steam-tegoed op het verkeerde account? Pech.',
    problem: () => 'Dat saldo kun je daarna niet meer verplaatsen.',
    solution: () => 'Log eerst in op het juiste Steam-account, en wissel dan je code in.',
    cta: ($) => `Steam Wallet-codes op ${site($)}`,
    problemProp: 'wrong', solutionProp: 'checklist',
    checklist: () => ['Juiste Steam-account', 'Dan pas de code', 'Code uit je mail'] },
  { id: 'ugc-39', theme: 'redeem', title: 'Gebruikersnaam typo', sku: R1,
    hook: () => 'Eén letter fout in je gebruikersnaam. Dat wil je niet.',
    problem: () => 'Dan zoekt de levering naar het verkeerde account.',
    solution: ($) => `Kopieer je ${$.field(R1)} rechtstreeks uit je profiel als je bestelt.`,
    cta: ($) => site($),
    problemProp: 'wrong', solutionProp: 'username' },
  { id: 'ugc-40', theme: 'redeem', title: 'Code delen', sku: S10,
    hook: () => 'Deel je cadeaucode nooit in een groepsapp.',
    problem: () => 'Wie hem het eerst inwisselt, heeft hem.',
    solution: () => 'Je code komt alleen in je eigen mail. Houd hem daar tot je hem gebruikt.',
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'mailcode' },

  // ── I. Andere games ──────────────────────────────────────────────────────
  { id: 'ugc-41', theme: 'games', title: 'Valorant Points', sku: 'VAL-2050', skus: ['VAL-1000', 'VAL-2050'],
    ok: ($) => $.per1k('VAL-2050') < $.per1k('VAL-1000'),
    hook: () => 'Die ene skin. En net te weinig VP.',
    problem: () => 'In de game zie je niet wat het per duizend kost.',
    solution: ($) => `Duizend VP voor ${$.p('VAL-1000')}. ${$.size('VAL-2050')} VP voor ${$.p('VAL-2050')}.`,
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'packs', packs: ['VAL-1000', 'VAL-2050'] },
  { id: 'ugc-42', theme: 'games', title: 'Discord Nitro', sku: 'NITRO-1Y', skus: ['NITRO-1M', 'NITRO-1Y'],
    ok: ($) => 12 * $.c('NITRO-1M') > $.c('NITRO-1Y'),
    hook: () => 'Elke maand Nitro opnieuw kopen?',
    problem: ($) => `Twaalf keer een maand is ${$.m(12 * $.c('NITRO-1M'))}.`,
    solution: ($) => `Een maand kost ${$.p('NITRO-1M')}. Een jaar ${$.p('NITRO-1Y')}.`,
    cta: ($) => `Reken het na: ${site($)}`,
    problemProp: 'receipts', receipt: 'NITRO-1M', count: 12, solutionProp: 'packs', packs: ['NITRO-1M', 'NITRO-1Y'] },
  { id: 'ugc-43', theme: 'games', title: 'Minecraft', sku: 'MC-3500', skus: ['MC-1720', 'MC-3500'],
    ok: ($) => $.per1k('MC-3500') < $.per1k('MC-1720'),
    hook: () => 'Minecoins kopen in kleine stukjes?',
    problem: () => 'Dan betaal je per coin het meest.',
    solution: ($) => `${$.size('MC-1720')} Minecoins: ${$.p('MC-1720')}. ${$.size('MC-3500')}: ${$.p('MC-3500')}.`,
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'packs', packs: ['MC-1720', 'MC-3500'] },
  { id: 'ugc-44', theme: 'games', title: 'Clash of Clans', sku: 'COC-2500', skus: ['COC-500', 'COC-2500'],
    ok: ($) => 5 * $.c('COC-500') > $.c('COC-2500'),
    hook: () => 'Ik kocht steeds vijfhonderd gems tegelijk.',
    problem: ($) => `${$.p('COC-500')} per keer. Het telt op.`,
    solution: ($) => `${$.size('COC-2500')} gems kost ${$.p('COC-2500')}. Vijf keer vijfhonderd is ${$.m(5 * $.c('COC-500'))}.`,
    cta: ($) => site($),
    problemProp: 'receipts', receipt: 'COC-500', count: 5, solutionProp: 'packs', packs: ['COC-500', 'COC-2500'] },
  { id: 'ugc-45', theme: 'games', title: 'EA FC Points', sku: 'EAFC-12000', skus: ['EAFC-1600', 'EAFC-12000'],
    ok: ($) => $.per1k('EAFC-12000') < $.per1k('EAFC-1600'),
    hook: () => 'Ultimate Team leegt je portemonnee.',
    problem: () => 'Zeker als je steeds een klein pakje Points koopt.',
    solution: ($) => `${$.size('EAFC-1600')} FC Points: ${$.p('EAFC-1600')}. ${$.size('EAFC-12000')}: ${$.p('EAFC-12000')}. Reken het per duizend.`,
    cta: ($) => site($),
    problemProp: 'receipts', receipt: 'EAFC-1600', solutionProp: 'packs', packs: ['EAFC-1600', 'EAFC-12000'] },

  // ── J. Mythes en checks ──────────────────────────────────────────────────
  { id: 'ugc-46', theme: 'myths', title: 'Codes online zijn nep', sku: V28,
    hook: () => '"Codes online kopen is altijd nep." Hoor ik vaak.',
    problem: () => 'Daarom kijk ik eerst naar één ding.',
    solution: () => 'Wat er gebeurt als het niet komt. Bij ForgeMarket: niet geleverd, geld terug.',
    cta: ($) => $.site('forgemarket.nl/refunds'),
    problemProp: 'worry', solutionProp: 'refund' },
  { id: 'ugc-47', theme: 'myths', title: 'Je moet een account hebben', sku: R1,
    hook: () => 'Je hoeft geen account te maken om te bestellen.',
    problem: () => 'Veel mensen denken dat het moet, en haken af.',
    solution: () => 'Bij ForgeMarket reken je af als gast.',
    cta: ($) => site($),
    problemProp: 'signup', solutionProp: 'guest' },
  { id: 'ugc-48', theme: 'myths', title: 'Groot pak is zonde', sku: V13, skus: [V1, V13],
    ok: ($) => $.per1k(V13) < $.per1k(V1),
    hook: () => '"Een groot pak is zonde van je geld." Klopt niet altijd.',
    problem: () => 'Per duizend betaal je bij kleine pakjes juist meer.',
    solution: ($) => `V-Bucks: ${$.per(V1)} per duizend in het kleinste pak, ${$.per(V13)} in het grootste.`,
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'packs', packs: [V1, V13] },
  { id: 'ugc-49', theme: 'myths', title: 'Het checklistje', sku: R1,
    hook: () => 'Mijn checklist voordat ik game-tegoed koop.',
    problem: () => 'Wachtwoord? Account nodig? Wat als het niet komt?',
    solution: () => 'ForgeMarket: geen wachtwoord, afrekenen als gast, niet geleverd is geld terug.',
    cta: ($) => site($),
    problemProp: 'text', solutionProp: 'checklist',
    checklist: () => ['Geen wachtwoord', 'Afrekenen als gast', 'Niet geleverd? Geld terug'] },
  { id: 'ugc-50', theme: 'myths', title: 'Eerlijk antwoord', sku: R1,
    hook: () => '"Waar koop jij je Robux?" Eerlijk antwoord.',
    problem: () => 'Ergens waar ze nooit mijn wachtwoord vragen.',
    solution: ($) => `Op ForgeMarket alleen mijn gebruikersnaam. Duizend Robux, ${$.p(R1)}.`,
    cta: () => 'Link in bio.',
    problemProp: 'scam', solutionProp: 'username' },
];

export const BEATS = ['hook', 'problem', 'solution', 'cta'];
/* The four windows the brief sets, in seconds: a beat holds at least this long. */
export const BEAT_DUR = { hook: 2, problem: 3, solution: 5, cta: 4 };

/** Every product a script reads. */
export const skusOf = (s) => [...new Set([s.sku, ...(s.skus || []), ...(s.packs || []), ...(s.receipt ? [s.receipt] : [])])];
